### ISSUE TITLE
Comply with rate limiting

### ISSUE THREAD

**Issue by Neztore** [ptrcko2/PublicNitroAPI#1]
Hi, I like the look of this! Seems very useful.
Please comply with rate limiting in your sample model by either checking for rate limit-related errors, or actively restricting the number of requests (or, preferably, both!)

This can be achieved by creating a `requestsMade` number, and a `madeSince` variable, and cutting it off if more than 30 are made in a minute.

See the [API docs](https://verify.nezto.re/docs) for more information about rate limit errors

**Comment by ptrcko2** [comment]
Fixed! Thanks for the feedback.
